import{i as d,a as b,s as p}from"./assets/vendor-da73009b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const s={formElem:document.querySelector("#search"),spanElem:document.querySelector(".loader"),listElems:document.querySelector(".gallery"),btnElement:document.querySelector(".btn")};function w(){s.spanElem.classList.remove("hidden")}function h(){s.spanElem.classList.add("hidden")}function v(){s.btnElement.classList.remove("hidden")}function g(){s.btnElement.classList.add("hidden")}function y(){c>=u?(g(),u&&d.show({message:"We're sorry, but you've reached the end of search results.",position:"center",displayMode:"once",maxWidth:500,imageWidth:600})):v()}function l(a){h(),s.listElems.innerHTML=" ",d.show({message:a,position:"center",displayMode:"once",maxWidth:500,imageWidth:600})}function P(){const e=s.listElems.children[0].getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})}const q=b.create({baseURL:"https://pixabay.com"});async function f(a,e){try{const i={key:"44483599-b54948657c32ff6f545b82f23",q:a,image_type:"photo",pretty:!0,orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await q.get("/api/",{params:i})).data}catch{l("Warning! Enter a word for the query, please.")}}function E(a){return a.map(({largeImageURL:e,webformatURL:i,tags:n,likes:t,views:r,comments:o,downloads:L})=>`<li class="gallery-item">
	<a class="gallery-link" href="${e}">
		<img 
			class="gallery-image" 
			src="${i}" 
			alt="${n}"
            
			/>
      <ul class="list-img">
      <li class="item-img"><p class="title-img">Likes</p><p class="text-img">${t}</p></li> 
      <li class="item-img"><p class="title-img">Views</p><p class="text-img">${r}</p></li> 
      <li class="item-img"><p class="title-img">Comments</p><p class="text-img">${o}</p></li> 
      <li class="item-img"><p class="title-img">Downloads</p><p class="text-img">${L}</p></li>     
      </ul>
	</a>
</li>`).join("")}let m="",c=1,u=1;const x=15;s.formElem.addEventListener("submit",async a=>{if(a.preventDefault(),m=a.target.elements.search.value.trim(),!m){l("Sorry, there are no images matching your search query. Please try again!");return}c=1,w();try{const e=await f(m,c);if(u=Math.ceil(e.totalHits/x),e.hits.length===0){l("Sorry, there are no images matching your search query. Please try again!"),s.inputElem.value="";return}const i=await E(e.hits);s.listElems.innerHTML=i,new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}catch{l("Sorry, there are no images matching your search query. Please try again!")}y(),h(),s.formElem.elements.search.value=""});s.btnElement.addEventListener("click",async a=>{c++,g();try{const e=await f(m,c),i=await E(e.hits);s.listElems.insertAdjacentHTML("beforeend",i),new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh(),P()}catch{l("Sorry, there are no images matching your search query. Please try again!")}y()});
//# sourceMappingURL=commonHelpers.js.map
